Vagrant.require_version ">= 1.9.0"
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.synced_folder "../", "/test"
  config.vm.provision "shell", inline: <<-SHELL
	cd /test
	./fetch
	./init
  SHELL
end
